/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lexico.jflex</tt>
 */
class lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\67\1\1\1\1\1\1\22\0\1\2\1\35\1\72"+
    "\1\4\1\71\1\4\1\36\1\0\1\37\1\40\1\30\1\26\1\45"+
    "\1\27\1\70\1\31\12\6\1\43\1\44\1\33\1\34\1\32\1\0"+
    "\1\4\1\63\1\3\1\65\1\66\1\60\2\3\1\64\1\53\3\3"+
    "\1\57\1\54\1\55\2\3\1\62\1\52\1\61\6\3\1\41\1\0"+
    "\1\42\1\0\1\56\1\0\1\20\1\22\1\15\1\14\1\7\1\24"+
    "\1\50\1\3\1\16\2\3\1\21\1\17\1\10\1\13\1\46\1\3"+
    "\1\12\1\25\1\11\1\47\1\23\1\3\1\51\2\3\1\0\1\5"+
    "\10\0\1\1\u1fa2\0\1\1\1\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\7\2\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\3\1\1\12\1\13\1\14"+
    "\1\15\1\1\1\16\1\17\6\2\2\1\1\20\1\0"+
    "\12\2\1\21\1\22\1\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\2\2\1\32\4\2\2\0\1\33"+
    "\1\34\12\2\1\35\11\2\1\0\16\2\1\36\5\2"+
    "\1\37\4\2\1\40\4\2\1\41\1\42\6\2\1\43"+
    "\1\44\1\45\1\46\2\2\1\47\13\2\1\50\5\2"+
    "\1\51\1\52\1\53\2\2\1\54\1\55\1\56\1\57"+
    "\3\2\1\60\1\61\1\62\1\2\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\73\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\73\0\73\0\73"+
    "\0\73\0\u049c\0\73\0\73\0\u04d7\0\u0512\0\u054d\0\u0588"+
    "\0\u05c3\0\u05fe\0\u0639\0\u0674\0\73\0\u06af\0\u06ea\0\u0725"+
    "\0\u0760\0\u079b\0\u07d6\0\u0811\0\u084c\0\u0887\0\u08c2\0\u08fd"+
    "\0\73\0\73\0\u0938\0\73\0\73\0\73\0\73\0\73"+
    "\0\73\0\73\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a"+
    "\0\u0ad5\0\u0b10\0\u0674\0\73\0\u06af\0\u0b4b\0\u0b86\0\u0bc1"+
    "\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\73"+
    "\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36"+
    "\0\u0f71\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e"+
    "\0\u1149\0\u1184\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6"+
    "\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d\0\u1448\0\73\0\u1483"+
    "\0\u14be\0\u14f9\0\u1534\0\166\0\u156f\0\u15aa\0\u15e5\0\u1620"+
    "\0\166\0\166\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782"+
    "\0\166\0\166\0\166\0\166\0\u17bd\0\u17f8\0\166\0\u1833"+
    "\0\u186e\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0\0\u1a0b"+
    "\0\u1a46\0\u1a81\0\166\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8"+
    "\0\166\0\166\0\166\0\u1be3\0\u1c1e\0\166\0\166\0\166"+
    "\0\166\0\u1c59\0\u1c94\0\u1ccf\0\166\0\166\0\166\0\u1d0a"+
    "\0\166";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\0\1\2\1\3\1\2\1\4\1\5\1\6"+
    "\4\3\1\7\1\10\1\11\3\3\1\12\1\13\1\14"+
    "\1\3\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\3\3\1\36\1\37\2\3\1\2\1\40"+
    "\4\3\1\41\1\3\1\42\2\2\1\43\1\44\76\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\21\3\1\0"+
    "\1\3\7\0\1\45\73\0\1\5\61\0\1\46\5\0"+
    "\5\3\1\47\15\3\1\0\3\3\3\0\2\3\7\0"+
    "\3\3\1\50\15\3\1\0\1\3\5\0\4\3\1\51"+
    "\16\3\1\0\3\3\3\0\2\3\7\0\21\3\1\0"+
    "\1\3\5\0\15\3\1\52\1\53\4\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\14\3"+
    "\1\54\6\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\10\3\1\55\12\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\4\3"+
    "\1\56\10\3\1\57\5\3\1\0\3\3\3\0\2\3"+
    "\7\0\21\3\1\0\1\3\5\0\15\3\1\60\5\3"+
    "\1\0\3\3\3\0\2\3\7\0\21\3\1\0\1\3"+
    "\30\0\1\61\52\0\1\5\20\0\1\62\74\0\1\63"+
    "\75\0\1\64\72\0\1\65\72\0\1\66\72\0\1\67"+
    "\1\70\73\0\1\71\70\0\1\72\41\0\7\3\1\73"+
    "\13\3\1\0\3\3\3\0\2\3\7\0\1\3\1\74"+
    "\17\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\5\3\1\75\13\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\6\3\1\76"+
    "\12\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\5\3\1\77\13\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\15\3\1\100"+
    "\3\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\12\3\1\101\6\3\1\0\1\3\32\0"+
    "\1\102\44\0\24\103\1\0\3\103\3\0\2\103\7\0"+
    "\21\103\1\0\1\103\1\0\1\104\6\0\1\105\67\0"+
    "\6\3\1\106\14\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\6\3\1\107\14\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\12\3\1\110\10\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\11\3\1\111\11\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\15\3\1\112\5\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\1\113\20\3\1\0\1\3\5\0\10\3"+
    "\1\114\12\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\7\3\1\115\13\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\12\3"+
    "\1\116\10\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\16\3\1\117\4\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\4\0\24\63"+
    "\1\0\3\63\3\0\2\63\7\0\21\63\1\120\1\63"+
    "\5\0\10\3\1\121\2\3\1\122\7\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\17\3"+
    "\1\123\3\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\23\3\1\0\3\3\3\0\2\3"+
    "\7\0\6\3\1\124\12\3\1\0\1\3\5\0\23\3"+
    "\1\0\3\3\3\0\2\3\7\0\17\3\1\125\1\3"+
    "\1\0\1\3\5\0\23\3\1\0\3\3\3\0\2\3"+
    "\7\0\12\3\1\126\6\3\1\0\1\3\5\0\23\3"+
    "\1\0\3\3\3\0\2\3\7\0\4\3\1\127\12\3"+
    "\1\130\1\3\1\0\1\3\5\0\23\3\1\0\3\3"+
    "\3\0\2\3\7\0\4\3\1\131\14\3\1\0\1\3"+
    "\4\0\24\102\1\0\1\102\1\132\1\102\3\0\2\102"+
    "\7\0\23\102\5\0\4\3\1\133\16\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\13\3"+
    "\1\134\7\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\13\3\1\135\7\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\4\3"+
    "\1\136\16\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\22\3\1\137\1\0\3\3\3\0"+
    "\2\3\7\0\21\3\1\0\1\3\5\0\7\3\1\140"+
    "\1\141\12\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\16\3\1\142\4\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\11\3"+
    "\1\143\11\3\1\0\3\3\3\0\2\3\7\0\21\3"+
    "\1\0\1\3\5\0\13\3\1\144\7\3\1\0\3\3"+
    "\3\0\2\3\7\0\21\3\1\0\1\3\5\0\22\3"+
    "\1\145\1\0\3\3\3\0\2\3\7\0\21\3\1\0"+
    "\1\3\5\0\6\3\1\146\14\3\1\0\3\3\3\0"+
    "\2\3\7\0\21\3\1\0\1\3\5\0\20\3\1\147"+
    "\2\3\1\0\3\3\3\0\2\3\7\0\21\3\1\0"+
    "\1\3\5\0\16\3\1\150\4\3\1\0\3\3\3\0"+
    "\2\3\7\0\21\3\1\0\1\3\5\0\23\3\1\0"+
    "\3\3\3\0\2\3\7\0\7\3\1\151\11\3\1\0"+
    "\1\3\5\0\23\3\1\0\3\3\3\0\2\3\7\0"+
    "\14\3\1\152\4\3\1\0\1\3\5\0\23\3\1\0"+
    "\3\3\3\0\2\3\7\0\6\3\1\153\12\3\1\0"+
    "\1\3\5\0\23\3\1\0\3\3\3\0\2\3\7\0"+
    "\13\3\1\154\5\3\1\0\1\3\5\0\23\3\1\0"+
    "\3\3\3\0\2\3\7\0\12\3\1\155\6\3\1\0"+
    "\1\3\5\0\23\3\1\0\3\3\3\0\2\3\7\0"+
    "\20\3\1\156\1\0\1\3\4\0\24\102\1\0\1\102"+
    "\1\132\1\102\3\0\2\102\7\0\23\102\1\157\4\0"+
    "\7\3\1\160\13\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\4\3\1\161\16\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\14\3\1\162\6\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\5\3\1\163\15\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\4\3\1\164\16\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\13\3\1\165\7\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\7\3\1\166\13\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\4\3\1\167\16\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\15\3\1\170\5\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\10\3\1\171\12\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\10\3\1\172\12\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\4\3\1\173\16\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\15\3\1\174\5\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\13\3\1\175\7\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\10\3\1\176"+
    "\10\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\12\3\1\177\6\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\13\3\1\200"+
    "\5\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\15\3\1\201\3\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\14\3\1\202"+
    "\4\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\12\3\1\203\6\3\1\0\1\3\5\0"+
    "\10\3\1\204\12\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\5\3\1\205\15\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\15\3\1\206\5\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\15\3\1\207\5\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\14\3\1\210\6\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\6\3\1\211\14\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\15\3\1\212\5\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\11\3\1\213\11\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\2\3\1\214"+
    "\16\3\1\0\1\3\5\0\11\3\1\215\11\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\12\3\1\216\10\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\4\3\1\217\14\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\11\3\1\220"+
    "\7\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\14\3\1\221\4\3\1\0\1\3\5\0"+
    "\11\3\1\222\11\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\16\3\1\223\4\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\13\3\1\224\7\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\15\3\1\225\5\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\5\3\1\226\15\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\4\3\1\227\16\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\13\3\1\230\7\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\10\3\1\231\12\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\10\3\1\232\12\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\5\3\1\233\13\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\12\3\1\234"+
    "\6\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\15\3\1\235\3\3\1\0\1\3\5\0"+
    "\4\3\1\236\16\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\7\3\1\237\13\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\7\3\1\240\13\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\10\3\1\241\12\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\7\3\1\242\13\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\11\3\1\243\11\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\6\3\1\244"+
    "\12\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\4\3\1\245\14\3\1\0\1\3\5\0"+
    "\10\3\1\246\12\3\1\0\3\3\3\0\2\3\7\0"+
    "\21\3\1\0\1\3\5\0\10\3\1\247\12\3\1\0"+
    "\3\3\3\0\2\3\7\0\21\3\1\0\1\3\5\0"+
    "\23\3\1\0\3\3\3\0\2\3\7\0\13\3\1\250"+
    "\5\3\1\0\1\3\5\0\23\3\1\0\3\3\3\0"+
    "\2\3\7\0\7\3\1\251\11\3\1\0\1\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7493];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\6\1\4\11\1\1\2\11"+
    "\10\1\1\11\1\0\12\1\2\11\1\0\7\11\7\1"+
    "\2\0\1\11\13\1\1\11\11\1\1\0\24\1\1\11"+
    "\72\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder string = new StringBuilder();
  
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }
    private Symbol symbol(int type, Object value) {

    return new Symbol(type, yyline+1, yycolumn+1, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 204) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 52: break;
          case 2: 
            { return symbol(sym.ID,new String(yytext()));
            }
          case 53: break;
          case 3: 
            { return symbol(sym.ENTEROVAL,new String(yytext()));
            }
          case 54: break;
          case 4: 
            { return symbol(sym.SUM);
            }
          case 55: break;
          case 5: 
            { return symbol(sym.RES);
            }
          case 56: break;
          case 6: 
            { return symbol(sym.MUL);
            }
          case 57: break;
          case 7: 
            { return symbol(sym.DIV);
            }
          case 58: break;
          case 8: 
            { return symbol(sym.MAYOR);
            }
          case 59: break;
          case 9: 
            { return symbol(sym.MENOR);
            }
          case 60: break;
          case 10: 
            { return symbol(sym.PARA);
            }
          case 61: break;
          case 11: 
            { return symbol(sym.PARC);
            }
          case 62: break;
          case 12: 
            { return symbol(sym.CORA);
            }
          case 63: break;
          case 13: 
            { return symbol(sym.CORC);
            }
          case 64: break;
          case 14: 
            { return symbol(sym.FINL);
            }
          case 65: break;
          case 15: 
            { return symbol(sym.COMA);
            }
          case 66: break;
          case 16: 
            { return symbol(sym.OR);
            }
          case 67: break;
          case 17: 
            { return symbol(sym.AUMENTO);
            }
          case 68: break;
          case 18: 
            { return symbol(sym.DISMINUCION);
            }
          case 69: break;
          case 19: 
            { return symbol(sym.MAYORIGUAL);
            }
          case 70: break;
          case 20: 
            { return symbol(sym.MENORIGUAL);
            }
          case 71: break;
          case 21: 
            { return symbol(sym.IGUAL);
            }
          case 72: break;
          case 22: 
            { return symbol(sym.DIFERENTE);
            }
          case 73: break;
          case 23: 
            { return symbol(sym.NEGACION);
            }
          case 74: break;
          case 24: 
            { return symbol(sym.AND);
            }
          case 75: break;
          case 25: 
            { return symbol(sym.ASIGNAR);
            }
          case 76: break;
          case 26: 
            { return symbol(sym.SI);
            }
          case 77: break;
          case 27: 
            { return symbol(sym.LITERAR,new String(yytext()));
            }
          case 78: break;
          case 28: 
            { return symbol(sym.DECIMALVAL,new String(yytext()));
            }
          case 79: break;
          case 29: 
            { return symbol(sym.DDIAGCOM,new String(yytext()));
            }
          case 80: break;
          case 30: 
            { return symbol(sym.SINO);
            }
          case 81: break;
          case 31: 
            { return symbol(sym.COMVA,new String(yytext()));
            }
          case 82: break;
          case 32: 
            { return symbol(sym.CLASE);
            }
          case 83: break;
          case 33: 
            { return symbol(sym.VACIO,new String(yytext()));
            }
          case 84: break;
          case 34: 
            { return symbol(sym.FALSO,new String(yytext()));
            }
          case 85: break;
          case 35: 
            { return symbol(sym.HASTA);
            }
          case 86: break;
          case 36: 
            { return symbol(sym.HACER);
            }
          case 87: break;
          case 37: 
            { return symbol(sym.DESDE);
            }
          case 88: break;
          case 38: 
            { return symbol(sym.ENTERO,new String(yytext()));
            }
          case 89: break;
          case 39: 
            { return symbol(sym.CADENA,new String(yytext()));
            }
          case 90: break;
          case 40: 
            { return symbol(sym.DECIMAL,new String(yytext()));
            }
          case 91: break;
          case 41: 
            { return symbol(sym.PRIVADO,new String(yytext()));
            }
          case 92: break;
          case 42: 
            { return symbol(sym.PUBLICO,new String(yytext()));
            }
          case 93: break;
          case 43: 
            { return symbol(sym.SINO_SI);
            }
          case 94: break;
          case 44: 
            { return symbol(sym.EXTIENDE);
            }
          case 95: break;
          case 45: 
            { return symbol(sym.IMPRIMIR);
            }
          case 96: break;
          case 46: 
            { return symbol(sym.IMPORTAR);
            }
          case 97: break;
          case 47: 
            { return symbol(sym.BOOLEANO,new String(yytext()));
            }
          case 98: break;
          case 48: 
            { return symbol(sym.MIENTRAS);
            }
          case 99: break;
          case 49: 
            { return symbol(sym.VERDADERO,new String(yytext()));
            }
          case 100: break;
          case 50: 
            { return symbol(sym.PROTEGIDO,new String(yytext()));
            }
          case 101: break;
          case 51: 
            { return symbol(sym.SINCREMENTO);
            }
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java lexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        lexico scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new lexico(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
