
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 10 23:47:22 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AUMENTO = 6;
  public static final int FINL = 20;
  public static final int PUBLICO = 43;
  public static final int ASIGNAR = 19;
  public static final int SINO_SI = 25;
  public static final int RES = 3;
  public static final int DECIMALVAL = 36;
  public static final int IMPRIMIR = 32;
  public static final int ENTERO = 47;
  public static final int PATH = 40;
  public static final int SI = 24;
  public static final int DIFERENTE = 13;
  public static final int DDIAGCOM = 41;
  public static final int DESDE = 29;
  public static final int HASTA = 30;
  public static final int PRIVADO = 46;
  public static final int MENORIGUAL = 11;
  public static final int AND = 15;
  public static final int IGUAL = 12;
  public static final int ENTEROVAL = 39;
  public static final int SINO = 26;
  public static final int OR = 14;
  public static final int MIENTRAS = 27;
  public static final int EXTIENDE = 23;
  public static final int DIV = 5;
  public static final int COMVA = 44;
  public static final int IMPORTAR = 21;
  public static final int ID = 52;
  public static final int MAYORIGUAL = 10;
  public static final int DECIMAL = 48;
  public static final int EOF = 0;
  public static final int CLASE = 22;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MUL = 4;
  public static final int CADENA = 49;
  public static final int NEGACION = 16;
  public static final int MENOR = 9;
  public static final int LITERAR = 42;
  public static final int MAYOR = 8;
  public static final int SINCREMENTO = 31;
  public static final int VACIO = 51;
  public static final int FALSO = 37;
  public static final int HACER = 28;
  public static final int SUM = 2;
  public static final int BOOLEANO = 50;
  public static final int PROTEGIDO = 45;
  public static final int PARC = 18;
  public static final int DISMINUCION = 7;
  public static final int PARA = 17;
  public static final int VERDADERO = 38;
  public static final int CORC = 34;
  public static final int CORA = 33;
}

