
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 08 19:34:05 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int EPAQUETEC = 13;
  public static final int ERUTA = 8;
  public static final int EPROYECTO = 2;
  public static final int ENOMBRE = 4;
  public static final int ERUTAC = 9;
  public static final int ENOMBREC = 5;
  public static final int ECREACIONC = 7;
  public static final int ECREACION = 6;
  public static final int EPROYECTOC = 3;
  public static final int EPAQUETE = 12;
  public static final int EARCHSC = 15;
  public static final int EOF = 0;
  public static final int TEXTO = 16;
  public static final int error = 1;
  public static final int EARCHIVOC = 11;
  public static final int EARCHIVO = 10;
  public static final int PATH = 17;
  public static final int EARCHS = 14;
}

